FROM node:16.10-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install
COPY . .
RUN npm run build

FROM byjg/nginx-extras:1.21
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/cert /etc/remrratality.com
COPY --from=build /app/dist /usr/share/nginx/html