version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: remrratality-redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379

  postgres:
    image: postgres:latest
    container_name: remrratality-postgres
    env_file:
      - .env
    volumes:
      - ./data/init/postgres/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
      - ./data/db/postgres:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

  mongo:
    image: mongo:latest
    container_name: remrratality-mongo
    env_file:
      - .env
    volumes:
      - ./data/init/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db/mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017

  frontend:
    build:
      context: ./frontend
    container_name: mrratality-frontend
    command: npm run serve
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080

  backend:
    build:
      context: ./backend
    container_name: mrratality-backend
    command: go run cmd/backend/main.go
    env_file:
      - .env.backend
    volumes:
      - ./backend:/app
    ports:
      - 8081:8080
    depends_on:
      - redis
      - postgres
      - mongo
      - frontend
