version: "3.8"

services:
  redis:
    image: redis:6.2
    container_name: remrratality-redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379

  postgres:
    image: postgres:14.0
    container_name: remrratality-postgres
    env_file:
      - .env
    volumes:
      - ./data/init/postgres/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
      - ./data/db/postgres:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

  mongo:
    image: mongo:5.0
    container_name: remrratality-mongo
    env_file:
      - .env
    volumes:
      - ./data/init/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db/mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017

  adminer:
    image: dockette/adminer:full
    container_name: remrratality-adminer
    env_file:
      - .env
    ports:
      - 8000:80

  frontend_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: remrratality-frontend-dev
    command: npm run serve
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080

  frontend_prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: remrratality-frontend-prod
    ports:
      - 8082:80

  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: remrratality-backend-dev
    command: go run cmd/backend/main.go
    env_file:
      - .env.backend
    volumes:
      - ./backend:/app
    ports:
      - 8081:8080
    depends_on:
      - redis
      - postgres
      - mongo
      - adminer

  backend_prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: remrratality-backend-prod
    env_file:
      - .env.backend
    ports:
      - 8081:8080
    depends_on:
      - redis
      - postgres
      - mongo
      - adminer
